### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by bobmorane83** [antoineguilbert/android-messages-for-desktop#30]
Hello,

I was using the 1.1.3 without issues, but today no more Emoji displayed. (Macbook pro M1, Monterey 12.5.1) 

![Capture d’écran 2022-11-24 à 11 47 35](https://user-images.githubusercontent.com/5717227/203765932-d076784c-5647-4a4c-98c0-f5013fa0639c.png)

I updated to 1.1.7, but same display problem.  
I can click on emoji, but they are just not displayed, even when writing the message. The emoji are correctly sent.

![Capture d’écran 2022-11-24 à 11 58 46](https://user-images.githubusercontent.com/5717227/203767716-d3de2c09-84a1-49bf-90b8-bfd21903a928.png)

![Capture d’écran 2022-11-24 à 11 58 55](https://user-images.githubusercontent.com/5717227/203767751-44288a37-3f1c-4272-b4a7-367e84af0345.png)

No problem with Google chat.

![Capture d’écran 2022-11-24 à 11 47 49](https://user-images.githubusercontent.com/5717227/203766544-5a5fd3fa-55cb-4e92-b9cb-affce555f6d0.png)

Let me know if I can help,
BR

**Comment by chdrummer** [comment]
I'm having the same issue on 1.1.7

**Comment by antoineguilbert** [comment]
Hello, 

I've also the same issue. I'm currently investigating where is the problem. 
If you've an idea, help is welcome ! 👍 

Thanks
