### ISSUE TITLE
error on startup 

### ISSUE THREAD

**Issue by chdrummer** [antoineguilbert/android-messages-for-desktop#31]
This error started a few days ago. Running the latest release for windows. 

![image](https://user-images.githubusercontent.com/49802735/233812794-e3685fa1-25f0-4e81-a21b-71d87ef2b78e.png)

**Comment by antoineguilbert** [comment]
Hello, 

Please update to the last version here : https://github.com/antoineguilbert/android-messages-for-desktop/releases/tag/v2.0.0

Thanks

**Comment by chdrummer** [comment]
I'm on windows, there's only a .dmg for version 2.0.

**Comment by chdrummer** [comment]
> Hello,
> 
> Please update to the last version here : https://github.com/antoineguilbert/android-messages-for-desktop/releases/tag/v2.0.0
> 
> Thanks

Is there anyway you could release an .exe version for 2.0? Thank you!!
